services:
  postweb.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: PostWeb.Api/Docker
    depends_on:
      - db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        
  db:
    container_name: 'mssql'
    ports:
      - "5433:1433"
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    volumes:
      - mssqldata:/var/opt/mssql